
name: Publish to Pub.dev

on:
  push:
    branched: ['master']

jobs:
  version:
    name: Code Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test --coverage

#      - name: Publish to Pub.dev
#        run: pub publish --dry-run

      - name: push build status to Slack
          uses: 8398a7/action-slack@v3
          with:
            status: ${{ job.status }}
            fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          if: always()

